# Generated by Django 4.1 on 2025-12-11 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Post')),
                ('description', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('RECEIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver1', to='instagram_app.user')),
                ('SENDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender1', to='instagram_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='instagram_app.post')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='instagram_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('RECEIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='instagram_app.user')),
                ('SENDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='instagram_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=500)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('POST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='instagram_app.post')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='instagram_app.user')),
            ],
        ),
    ]
